# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recommendations.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'recommendations.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15recommendations.proto\x12\x0frecommendations\"\xba\x01\n\x15RecommendationRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12U\n\x10user_preferences\x18\x02 \x03(\x0b\x32;.recommendations.RecommendationRequest.UserPreferencesEntry\x1a\x36\n\x14UserPreferencesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"i\n\x0eRecommendation\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x14\n\x0cproduct_name\x18\x02 \x01(\t\x12\x17\n\x0frelevance_score\x18\x03 \x01(\x02\x12\x14\n\x0cproduct_json\x18\x04 \x01(\t\"R\n\x16RecommendationResponse\x12\x38\n\x0frecommendations\x18\x01 \x03(\x0b\x32\x1f.recommendations.Recommendation2~\n\x15RecommendationService\x12\x65\n\x12GetRecommendations\x12&.recommendations.RecommendationRequest\x1a\'.recommendations.RecommendationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recommendations_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECOMMENDATIONREQUEST_USERPREFERENCESENTRY']._loaded_options = None
  _globals['_RECOMMENDATIONREQUEST_USERPREFERENCESENTRY']._serialized_options = b'8\001'
  _globals['_RECOMMENDATIONREQUEST']._serialized_start=43
  _globals['_RECOMMENDATIONREQUEST']._serialized_end=229
  _globals['_RECOMMENDATIONREQUEST_USERPREFERENCESENTRY']._serialized_start=175
  _globals['_RECOMMENDATIONREQUEST_USERPREFERENCESENTRY']._serialized_end=229
  _globals['_RECOMMENDATION']._serialized_start=231
  _globals['_RECOMMENDATION']._serialized_end=336
  _globals['_RECOMMENDATIONRESPONSE']._serialized_start=338
  _globals['_RECOMMENDATIONRESPONSE']._serialized_end=420
  _globals['_RECOMMENDATIONSERVICE']._serialized_start=422
  _globals['_RECOMMENDATIONSERVICE']._serialized_end=548
# @@protoc_insertion_point(module_scope)
